version: '3'
services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: jenkins
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - './jenkins:/jenkins'
      - './settings.xml/settings.xml:/jenkins/maven3/conf/settings.xml'